version: '3.8'

services:
  xtts-api-server:
    image: xtts-server
    ports:
      - "8020:8020"
    volumes:
      - ./output:/output
      - ./speakers:/speakers  # Bind mount the host-mounted speakers directory
      - ./xtts_models:/xtts_models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped 